manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/t0bybr
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # - name: miryoku
    #   url: https://github.com/t0bybr/miryoku_zmk.git
    #   revision: master
    #   path: miryoku_zmk
  self:
    path: config
